### ISSUE TITLE
Typo in magic command

### ISSUE THREAD

**Issue by larsonma** [jayurbain/DataScienceIntro#4]
@jayurbain 
Running the cell below produced an error for me. I believe it should be `%timeit np.random`

https://github.com/jayurbain/DataScienceIntro/blob/b09caa96a95d0c8e3ae7faa9aad88aee7a29f442/notebooks/4%20-%20Python%20Numpy.ipynb#L88

**Comment by jayurbain** [comment]
Thanks. That line should have had one % for line timeit not two for cell timeit. Corrected.
