### ISSUE TITLE
Resource missing

### ISSUE THREAD

**Issue by larsonma** [jayurbain/DataScienceIntro#6]
@jayurbain 
The resource that this link points to is missing. Without it as reference it is a little difficult to categorize Series as the correct datatype.

https://github.com/jayurbain/DataScienceIntro/blob/f31aff9e0fde7ce71fe12ca584121d63a435582e/labs/lab_2_eda/lab_2_eda_backpain.ipynb#L53

**Comment by jayurbain** [comment]
Reference is correct and works as intended.

**Comment by jayurbain** [comment]
The reference is correct and is what was intended.

Jay Urbain
