### ISSUE TITLE
Stanford Back Pain Survey PDF is missing

### ISSUE THREAD

**Issue by rnowling** [jayurbain/DataScienceIntro#7]
The lab 2 eda notebook contains a link to a Stanford Back Pain Survey PDF.  The PDF does not seem to be in the repository at the location indicated by the link.

**Comment by jayurbain** [comment]
Works for me and I have several students that have already submitted this assignment. Try doing a 'git pull' on this repository. I seem to recall updating this link ~1 week ago.
