### ISSUE TITLE
Image is missing from Lab_LinearRegression directory

### ISSUE THREAD

**Issue by larsonma** [jayurbain/DataScienceIntro#8]
When trying to read an image called linear_regression_residuals.png from file, I get an error saying `TypeError: a bytes-like object is required, not 'str'`. I think that this is happening because the image is not my directory.

Note: I got this error with the most recent version of the upstream/master code.

https://github.com/jayurbain/DataScienceIntro/blob/3adcc9fb0a02579dfeb6aa93bd6cc1b3216ff3b0/labs/Lab3_LinearRegression/Supervised%20Learning%20-%20%20Linear%20Regression.ipynb#L775

**Comment by jayurbain** [comment]
Thanks Mitchell. I've added the missing image file 'linear_regression_residuals.png' to the repository.

**Comment by jayurbain** [comment]
Thanks. I've updated the repository.

Jay Urbain
