### ISSUE TITLE
Wrong path to Default.csv

### ISSUE THREAD

**Issue by larsonma** [jayurbain/DataScienceIntro#9]
https://github.com/jayurbain/DataScienceIntro/blob/aec5576532278b5847a56f124d2d48cfeff1b1a7/labs/Lab5_Logistic_Regression/Supervised%20Learning%20-%20Logistic%20Regression.ipynb#L162

I believe the correct path to the Default.csv is `d = pd.read_csv('../../data/Default.csv')`

**Comment by jayurbain** [comment]
I added the data directory ~1 week ago.

You need to download the following directory:
labs/Lab5_Logistic_Regression/data

You can try the following:
# git fetch will download all the recent changes, but it will not put it in
your current checked out code (working area).
git fetch
#Followed by:
git checkout origin/master -- labs/Lab5_Logistic_Regression/data


Let me know if you have any questions.

Jay
